locks-review-team: opstooling
team-leads-team: opstooling
action-review-team: opstooling

rules:
  - name: Core developers
    check_type: changed_files
    condition:
      include: .*
    min_approvals: 1 # TODO: update to 2 after deployment to prod latest
    teams:
      - opstooling

  - name: CI files
    check_type: changed_files
    condition:
      # dictionary files are excluded
      include: ^\.gitlab-ci\.yml|helm\/.*
    min_approvals: 1
    teams:
      - ci
