name: 'PR Custom Review'
description: 'An action to enforce complex pull request approval cases'
author: 'paritytech'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  token:
    description: 'The token to be used for making requests such as requesting reviews'
  checks-reviews-api:
    description: 'The API to be used for processing the reviews. This input is only considered if "token" is not given.'
runs:
  using: 'docker'
  image: 'Dockerfile'
