common:
  env:
    GITHUB_ACCESS_TOKEN: ref+vault://kv/gitlab/parity/mirrors/cicd-parity-stg#GITHUB_ACCESS_TOKEN
  ingress:
    enabled: true
    className: ""
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-http01
      external-dns.alpha.kubernetes.io/target: traefik-external.parity-stg.parity.io.
      kubernetes.io/ingress.class: traefik-external
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: pcr.parity-stg.parity.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: pcr.parity-stg.parity.io
        hosts:
          - pcr.parity-stg.parity.io
